spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000

  stripe:
    secret-key: ${STRIPE_SECRET_KEY}
    publishable-key: ${STRIPE_PUBLISHABLE_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET_KEY}
